### ISSUE TITLE
Online banking payment issue

### ISSUE THREAD

**Issue by Userr017** [CheckoutFinland/plugin-magento2#3]
There maybe a issue with the module because doesn't go to the bank online payment provider page what you are choosed. This problem is happened many times. 

1. Selects the bank what you want to use for online payment.

2. Click button "Place order".

3. It goes directly to the order success page and order can not be paid using online banking payment. 

When it doesn't go to online bank payment provider page can see using developer mode error notification

![error (2)](https://user-images.githubusercontent.com/26794034/63796438-be3e7480-c90e-11e9-9c20-4e3017bec2e5.png)

This is important soon as possible fix if module is this issue! I have version magento 2.3.2.

The previous module version did not have this problem. https://github.com/CheckoutFinland/plugin-magento2.x

**Comment by pomppa** [comment]
Hello @Userr017 

We were unable to reproduce this issue on Magento 2.3.2 open source version with sample data installed and without any third party modules. Test credentials were used. Order was confirmed and payment was processed as it should. 

This issue you encounter is because of some configuration file and invalid 'action' node in it. In this module there is not even action node on any of the configuration files, so I'm guessing this issue is because of some other module. Please try to reproduce the issue with disabling all of those 3rd party modules and just keep the Checkout-module enabled. If you are able to reproduce this then, please provide the steps.

Thanks!
Tuomas

**Comment by timotarvainen** [comment]
![image](https://user-images.githubusercontent.com/26997785/64428406-52050300-d0bc-11e9-90a3-85f112c9fcef.png)
![image](https://user-images.githubusercontent.com/26997785/64428421-58937a80-d0bc-11e9-9b4a-62a0dad4e294.png)
![image](https://user-images.githubusercontent.com/26997785/64428430-5df0c500-d0bc-11e9-91a9-311fc3b41260.png)
![image](https://user-images.githubusercontent.com/26997785/64428439-61844c00-d0bc-11e9-9ff3-8b51be9080e5.png)
![image](https://user-images.githubusercontent.com/26997785/64428497-837dce80-d0bc-11e9-885c-26e3dbaceb76.png)

**Comment by MAleksei** [comment]
Hello @Userr017,

We have tested it with 2.3.0 ugpraded to 2.3.2 and with clean 2.3.2 install. 

Most likely issue is caused by some 3rd party module or theme in your setup which is trying to add something to the layout.  

Do you have any 3rd party modules which might affect checkout page layout ?

Best regards,
Aleksei

**Comment by Userr017** [comment]
Maybe it is reason someone my extension. Needed testing more.

**Comment by Userr017** [comment]
I don't know how solve this issue? I have disabled all custom modules.

When it goes directly to order success page and cannot pay order, can see debug.log.

[2019-09-17 12:34:59] main.DEBUG: {"stamp":"d7e5856a2431dade9429a12a067c70f97fac0493d75a995ed0b6da342e7a6ffc","reference":"2000000611","amount":195,"currency":"EUR","language":"FI","items":[{"unitPrice":195,"units":1,"vatPercentage":0,"description":"test","productCode":"test","deliveryDate":"2019-09-17"},{"unitPrice":0,"units":1,"vatPercentage":0,"description":"Posti - Arvioitu toimitusaika 15-20 arkip\u00e4iv\u00e4\u00e4","productCode":"","deliveryDate":"2019-09-17"}],"customer":{"firstName":"aaa123","lastName":"bbb123","phone":"000000","email":"email@hotmail.com"},"invoicingAddress":{"streetAddress":"Osoite 1","postalCode":"90250","city":"Oulu","country":"Suomi","county":"Pohjois-Pohjanmaa"},"deliveryAddress":{"streetAddress":"Osoite 1","postalCode":"90250","city":"Oulu","country":"Suomi","county":"Pohjois-Pohjanmaa"},"redirectUrls":{"success":"https://mystore.com/fi/opcheckout/receipt/","cancel":"https://mystore.com/fi/opcheckout/receipt/"},"callbackUrls":{"success":"https://mystore.com/fi/opcheckout/receipt/","cancel":"https://mystore.com/fi/opcheckout/receipt/"}} [] []


This doesn't happen always but often it doesn't go to payment provider page, online bank, credit card, mobile pay etc....


All failed orders are Backend Sales/Orders/ Order - Pending Payment. Customer get order invoice message to email but cannot pay order.

All works without issues, using old module: https://github.com/CheckoutFinland/plugin-magento2.x

**Comment by Userr017** [comment]
There may be a reason that the whole website is not use https? So this problem no longer exists when I forced to use it.

I added it to the file .htaccess
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

**Comment by Userr017** [comment]
Again this problem occurs for some customers. I try to find that another developer who solving the problem.

**Comment by Userr017** [comment]
Resolved the issues removing the old "order comments" extension.

**Comment by loueranta** [comment]
@Userr017 Great that you found solution to this problem and thanks for letting us know the root cause! 👍
